---
title: "Data Export"
author: "Weihan Liu, Alexandre Gaubil"
date: "1/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
options(max.print=20)
library(Seurat)
library(tidyverse)
library(ggplot2)

LT.seu.day2 <- readRDS(file = "./data/in_vitro/RDS_objects/LT_seu_day2_ML_source_data.rds")
```

# Export

## All genes

```{r}
day2.all_cells.all_genes <- as.data.frame(LT.seu.day2@assays$RNA@data)
day2.all_cells.all_genes <- t(day2.all_cells.all_genes) %>% as.data.frame()

# Attach the final identity (label) to the data
day2.all_cells.all_genes$final.ident <- LT.seu.day2@meta.data$final.ident

day2.all_cells.all_genes.data <- subset(day2.all_cells.all_genes, select = -c(final.ident))
day2.all_cells.all_genes.feature <- subset(day2.all_cells.all_genes, select = c(final.ident))

# Export the df
day2.all_cells.all_genes.data <- subset(day2.all_cells.all_genes, select = -c(final.ident))
day2.all_cells.all_genes.feature <- subset(day2.all_cells.all_genes, select = c(final.ident))

write.table(day2.all_cells.all_genes.data,
            row.names = FALSE,
            col.names = FALSE,
            "./data/in_vitro/analyses/all_cells_all_genes_data.txt")
write.table(day2.all_cells.all_genes.feature,
            row.names = FALSE,
            col.names = FALSE,
            "./data/in_vitro/analyses/all_cells_all_genes_features.txt")

write.table(day2.all_cells.all_genes.data,
            row.names = FALSE,
            col.names = TRUE,
            "./data/in_vitro/analyses/all_cells_all_genes_data_headers.txt")
write.table(day2.all_cells.all_genes.feature,
            row.names = FALSE,
            col.names = TRUE,
            "./data/in_vitro/analyses/all_cells_all_genes_features_headers.txt")
```

## 2,000 most variable genes

```{r}
LT.seu.day2@assays$RNA@var.features
day2.all_cells.2000_var <- as.data.frame(LT.seu.day2@assays$RNA@data)

day2.all_cells.2000_var <- filter(day2.all_cells.2000_var,rownames(day2.all_cells.2000_var) %in% LT.seu.day2@assays$RNA@var.features)

day2.all_cells.2000_var <- t(day2.all_cells.2000_var) %>% as.data.frame()
day2.all_cells.2000_var$final.ident <- LT.seu.day2@meta.data$final.ident

day2.all_cells.2000_var

# Export the df
day2.all_cells.2000_var.data <- subset(day2.all_cells.2000_var, select = -c(final.ident))
day2.all_cells.2000_var.feature <- subset(day2.all_cells.2000_var, select = c(final.ident))

write.table(day2.all_cells.2000_var.data,
            row.names = FALSE,
            col.names = FALSE,
            "./data/in_vitro/analyses/all_cells_2000_var_data.txt")
write.table(day2.all_cells.2000_var.feature,
            row.names = FALSE,
            col.names = FALSE,
            "./data/in_vitro/analyses/all_cells_2000_var_features.txt")

write.table(day2.all_cells.2000_var.data,
            row.names = FALSE,
            col.names = TRUE,
            "./data/in_vitro/analyses/all_cells_2000_var_data_headers.txt")
write.table(day2.all_cells.2000_var.feature,
            row.names = FALSE,
            col.names = TRUE,
            "./data/in_vitro/analyses/all_cells_2000_var_features_headers.txt")
```